{
 "title": "Fitbit Monthly",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Resting HR",
   "type": "timeseries",
   "description": "Resting HR",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Resting HR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "restingHeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Band wearing ",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "alias": "Heart rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "SELECT mean(value) FROM \"heartrate\" WHERE $timeFilter GROUP BY time(2m) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "6" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Heart rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "SELECT moving_average(mean(\"value\"), 6) FROM \"heartrate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "6" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "Above 95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "select above from (SELECT moving_average(mean(\"value\"), 6) as above FROM \"heartrate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)) where above > 95",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "8" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "value", "operator": "=~", "value": "/^$RHR$/" }
     ]
    },
    {
     "alias": "Below RHR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "select below from (SELECT moving_average(mean(\"value\"), 6) as below FROM \"heartrate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)) where below < 60",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "8" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "value", "operator": "=~", "value": "/^$RHR$/" }
     ]
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "Heart rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "SELECT mean(\"value\") FROM \"heartrate\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "6" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "alias": "Light Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "minutesLightlyActive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Fair Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "minutesFairlyActive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    },
    {
     "alias": "Intense Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "minutesVeryActive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HR Zones",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "alias": "Fat Burn",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartRateZones",
     "select": [
      [
       { "params": [ "minutes" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=", "value": "Fat Burn" }
     ]
    },
    {
     "alias": "Cardio",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartRateZones",
     "select": [
      [
       { "params": [ "minutes" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=", "value": "Cardio" }
     ]
    },
    {
     "alias": "Peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartRateZones",
     "select": [
      [
       { "params": [ "minutes" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=", "value": "Peak" }
     ]
    }
   ]
  },
  {
   "title": "Sleep Pattern",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 38 },
   "targets": [
    {
     "alias": "Sleep levels",
     "measurement": "sleep_levels",
     "query": "SELECT sleep_type FROM sleep_levels WHERE short = false",
     "select": [
      [
       { "params": [ "sleep_type" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "short", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "All sleeps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sleep_type FROM sleep_levels",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep",
   "type": "graph",
   "gridPos": { "h": 11, "w": 17, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_deep" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_light\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_light" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "REM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_rem\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_light" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_awake\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_light" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Mid-day Sleep",
   "type": "graph",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 44 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = false AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_deep" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_light\") FROM \"sleep\" WHERE is_main_sleep = false AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_light" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "REM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_rem\") FROM \"sleep\" WHERE is_main_sleep = false AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_light" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_awake\") FROM \"sleep\" WHERE is_main_sleep = false AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_light" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Wake up time",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Wake up time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep_levels",
     "select": [
      [
       { "params": [ "seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hourly Steps",
   "type": "graph",
   "gridPos": { "h": 6, "w": 14, "x": 10, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Avg. Hourly Step Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hourly_steps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sleep start time",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 6, "w": 10, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "Sleep start time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep_levels",
     "select": [
      [
       { "params": [ "seconds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hourly steps > 250",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 5, "w": 14, "x": 10, "y": 61 },
   "targets": [
    {
     "alias": "Hourly steps > 250",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hourly_steps_sum",
     "select": [
      [
       { "params": [ "greater than 250" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hourly walk heatmap",
   "type": "marcusolsson-hourly-heatmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Hourly walk heatmap",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hourly_steps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Steps",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "steps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lazy Minutes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "alias": "Lazy minutes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "minutesSedentary",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Calories",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "calories",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Avg",
     "groupBy": [
      { "params": [ "24h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "Min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    },
    {
     "alias": "Resting HR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "restingHeartRate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Biking & Walking duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Biking Duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "activity",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " *1.6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "activityName", "operator": "=", "value": "Bike" },
      { "condition": "OR", "key": "activityName", "operator": "=", "value": "Outdoor Bike" }
     ]
    },
    {
     "alias": "Walking Duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "activity",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " *1.6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "activityName", "operator": "=", "value": "Walk" }
     ]
    },
    {
     "alias": "Run Duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "activity",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " *1.6" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "activityName", "operator": "=", "value": "Run" }
     ]
    }
   ]
  },
  {
   "title": "Distance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "distance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*1.60934" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Floors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short", "label": "Floors" }
   ],
   "targets": [
    {
     "alias": "Floors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "floors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Activity Calories",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "activityCalories",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Elevation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "elevation",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Battery Percentage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "deviceBatteryLevel",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hidden",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 },
   "collapsed": true,
   "panels": [
    {
     "title": "GPS data",
     "type": "pr0ps-trackmap-panel",
     "gridPos": { "h": 10, "w": 13, "x": 0, "y": 114 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "GPS_track",
       "query": "SELECT lat FROM GPS_track",
       "select": [
        [
         { "params": [ "lat" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ]
      },
      {
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" }
       ],
       "measurement": "GPS_track",
       "query": "SELECT long FROM GPS_track",
       "select": [
        [
         { "params": [ "long" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GPS data",
     "type": "table",
     "gridPos": { "h": 10, "w": 11, "x": 13, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "string" } },
     "targets": [
      {
       "alias": "ID",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" }
       ],
       "measurement": "GPS_track",
       "query": "SELECT lat FROM GPS_track",
       "select": [
        [
         { "params": [ "id" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ]
      },
      {
       "alias": "Type",
       "groupBy": [
        { "params": [ "1h" ], "type": "time" }
       ],
       "measurement": "GPS_track",
       "query": "SELECT lat FROM GPS_track",
       "select": [
        [
         { "params": [ "activity_name" ], "type": "field" },
         {
          "params": [],
          "type": "distinct"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}