{
 "title": "Fitbit Daily",
 "time": { "from": "now/d  - 2h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Last update time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUSNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Last update time",
     "measurement": "deviceBatteryLevel",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last update time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Last update time",
     "measurement": "deviceBatteryLevel",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last time Battery Level",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Battery Percentage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "deviceBatteryLevel",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last script run time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUSNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Last update time",
     "measurement": "last_database_update",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last script run time",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Last update time",
     "measurement": "last_database_update",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
   "options": {
    "content": "<center><h1>Heart 💓</h1></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Resting HR",
   "type": "gauge",
   "description": "Resting HR",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Resting HR",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "restingHeartRate",
     "query": "SELECT distinct(\"value\") FROM \"restingHeartRate\" WHERE $timeFilter GROUP BY time(1h) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Heart rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "SELECT moving_average(mean(\"value\"), 6) FROM \"heartrate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "6" ], "type": "moving_average" }
      ]
     ]
    },
    {
     "alias": "Above 95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "select above from (SELECT moving_average(mean(\"value\"), 6) as above FROM \"heartrate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)) where above > 95",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "8" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "value", "operator": "=~", "value": "/^$RHR$/" }
     ]
    },
    {
     "alias": "Below RHR",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "select below from (SELECT moving_average(mean(\"value\"), 6) as below FROM \"heartrate\" WHERE $timeFilter GROUP BY time($__interval) fill(null)) where below < 60",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "8" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "value", "operator": "=~", "value": "/^$RHR$/" }
     ]
    }
   ]
  },
  {
   "title": "Breathing Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "per minute" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "BPM avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "br",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "SpO2",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spo2",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spo2",
     "select": [
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    },
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "spo2",
     "select": [
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heart Rate",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 17 },
   "targets": [
    {
     "alias": "Heart rate",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartrate",
     "query": "SELECT mean(\"value\") FROM \"heartrate\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "6" ], "type": "moving_average" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<center><h1>Sleep 😴</h1></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Last day Sleep ",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Awake",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_awake\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_light" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "REM",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_rem\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_light" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "Light",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_light\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_light" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    },
    {
     "alias": "Deep",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "query": "SELECT distinct(\"minutes_deep\") FROM \"sleep\" WHERE is_main_sleep = true AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "minutes_deep" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "is_main_sleep", "operator": "=", "value": "true" }
     ]
    }
   ]
  },
  {
   "title": "Sleep Pattern",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 23 },
   "targets": [
    {
     "alias": "Sleep levels",
     "measurement": "sleep_levels",
     "query": "SELECT sleep_type FROM sleep_levels WHERE short = false",
     "select": [
      [
       { "params": [ "sleep_type" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "short", "operator": "=", "value": "false" }
     ]
    },
    {
     "alias": "All sleeps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sleep_type FROM sleep_levels",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Sleep Start time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Sleep Start time",
     "measurement": "sleep",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total duration in bed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Time in bed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "select": [
      [
       { "params": [ "time_in_bed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Asleep duration",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Time in bed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "select": [
      [
       { "params": [ "minutes_asleep" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Awake duration on bed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Time in bed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sleep",
     "select": [
      [
       { "params": [ "minutes_wake" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ "*60" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last Wake up time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsUS" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Wake up time",
     "measurement": "sleep",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 35 },
   "options": {
    "content": "<center><h1>Activity 🏋️</h1></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Activity over given duration",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 11, "x": 1, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Light Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "minutesLightlyActive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Fair Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "minutesFairlyActive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Intense Activity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "minutesVeryActive",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    {
     "alias": "Sedentary",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "minutesSedentary",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "HR Zones over given duration",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Fat Burn",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartRateZones",
     "select": [
      [
       { "params": [ "minutes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=", "value": "Fat Burn" }
     ]
    },
    {
     "alias": "Cardio",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartRateZones",
     "select": [
      [
       { "params": [ "minutes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=", "value": "Cardio" }
     ]
    },
    {
     "alias": "Peak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartRateZones",
     "select": [
      [
       { "params": [ "minutes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=", "value": "Peak" }
     ]
    },
    {
     "alias": "Normal",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "heartRateZones",
     "select": [
      [
       { "params": [ "minutes" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "zone", "operator": "=", "value": "Out of Range" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 45 },
   "options": {
    "content": "<center><h1>Exercises 💪</h1></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Given duration Steps",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Last day Steps",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "steps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Given duration Calories",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Calories",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "calories",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Given duration Floors",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Floors",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "floors",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Given duration Distance",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Distance",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "distance",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       { "params": [ " *1.60934" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Exercise duration of given period",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Walking",
     "measurement": "activity",
     "query": "SELECT \"duration\" FROM \"activity\" WHERE (\"activityName\" = 'Walk')",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityName", "operator": "=", "value": "Walk" }
     ]
    },
    {
     "alias": "Biking",
     "measurement": "activity",
     "query": "SELECT \"duration\" FROM \"activity\" WHERE (\"activityName\" = 'Bike' OR \"activityName\" = 'Outdoor Bike')",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityName", "operator": "=", "value": "Bike" },
      { "condition": "OR", "key": "activityName", "operator": "=", "value": "Outdoor Bike" }
     ]
    },
    {
     "alias": "Running",
     "measurement": "activity",
     "query": "SELECT \"duration\" FROM \"activity\" WHERE (\"activityName\" = 'Run')",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityName", "operator": "=", "value": "Run" }
     ]
    }
   ]
  },
  {
   "title": "Walking",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 9, "x": 10, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Walking",
     "measurement": "activity",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityName", "operator": "=", "value": "Walk" }
     ]
    }
   ]
  },
  {
   "title": "Given duration Lazy Minutes",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Lazy minutes",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "minutesSedentary",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Biking",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 9, "x": 10, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Biking",
     "measurement": "activity",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityName", "operator": "=", "value": "Bike" },
      { "condition": "OR", "key": "activityName", "operator": "=", "value": "Outdoor Bike" }
     ]
    }
   ]
  },
  {
   "title": "Running",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 9, "x": 10, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "Running",
     "measurement": "activity",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "activityName", "operator": "=", "value": "Run" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 59 },
   "options": {
    "content": "<center><h1>Hourly steps detailed 👟</h1></center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hourly Steps",
   "type": "table",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Avg. Hourly Step Count",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hourly_steps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "steps per minute",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 6, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Avg. Hourly Step Count",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hourly_steps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hourly steps > 250",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 15, "x": 6, "y": 68 },
   "targets": [
    {
     "alias": "Hourly steps > 250",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hourly_steps_sum",
     "select": [
      [
       { "params": [ "greater than 250" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "True Count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hourly_steps_sum",
     "query": "SELECT count(\"greater than 250\") FROM hourly_steps_sum WHERE  \"greater than 250\" = true AND $timeFilter ",
     "select": [
      [
       { "params": [ "greater than 250" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  }
 ]
}